version: '2'

volumes:
  database_data:
    driver: local

services:
  redis:
    image: redis
    ports:
    - 6379:6379

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hola
      - POSTGRES_PASSWORD=hola
      - POSTGRES_DB=holadb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data